ALLOWED_PLACE_TYPES = [
    "country",
    "city",
    "province",
    "region",
    "attraction",
    "beach",
    "island",
    "mountain",
    "bay",
    "river",
    "lake",
    "national_park",
    "museum",
    "temple",
    "pagoda",
    "market",
    "restaurant",
    "hotel",
    "transport",
    "event",
    "food",
    "culture",
    "general",
]

ALLOWED_CHUNK_TOPICS = [
    "overview",
    "attraction",
    "culture",
    "history",
    "food",
    "transportation",
    "accommodation",
    "activity",
    "itinerary",
    "shopping",
    "safety",
    "travel_tips",
    "weather",
    "cost",
    "general",
]

ALLOWED_TRAVEL_STYLES = [
    "culture",
    "history",
    "adventure",
    "relaxation",
    "nature",
    "food",
    "beach",
    "luxury",
    "budget",
    "family",
    "nightlife",
    "shopping",
    "photography",
    "local_experience",
]

ALLOWED_SUITABLE_FOR = [
    "families",
    "couples",
    "solo_travelers",
    "groups",
    "first_time_visitors",
    "backpackers",
    "luxury_travelers",
    "budget_travelers",
    "history_lovers",
    "culture_seekers",
    "food_lovers",
    "nature_lovers",
    "photography_lovers",
]

KNOWN_CITIES = [
    "Da Nang",
    "Hanoi",
    "Hoi An",
    "Hue",
    "Ho Chi Minh City",
    "Sa Pa",
    "Nha Trang",
]