"""initial

Revision ID: c37f93b458c6
Revises: 
Create Date: 2026-05-26 00:21:10.779811

"""
from typing import Sequence, Union

from alembic import op
from pgvector.sqlalchemy import VECTOR
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c37f93b458c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The Vector column type and ivfflat index below require pgvector.  Create
    # the extension as part of a fresh deployment instead of relying on a
    # manually prepared database.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Text(), nullable=True),
    sa.Column('source_name', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('cleaned_markdown', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('ingestion_status', sa.Text(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_hash', sa.String(length=64), nullable=True),
    sa.Column('source_chunk_id', sa.Text(), nullable=True),
    sa.Column('section_heading', sa.Text(), nullable=True),
    sa.Column('subsection_heading', sa.Text(), nullable=True),
    sa.Column('section_level', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('province', sa.Text(), nullable=True),
    sa.Column('place_name', sa.Text(), nullable=True),
    sa.Column('place_type', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_topic', sa.Text(), nullable=True),
    sa.Column('ai_tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_activities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_travel_styles', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_suitable_for', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_source', sa.Text(), nullable=True),
    sa.Column('metadata_confidence', sa.Float(), nullable=True),
    sa.Column('embedding', VECTOR(384), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_rag_chunks_document_chunk_index')
    )
    op.create_index('ix_rag_chunks_ai_activities', 'rag_chunks', ['ai_activities'], unique=False, postgresql_using='gin')
    op.create_index('ix_rag_chunks_ai_suitable_for', 'rag_chunks', ['ai_suitable_for'], unique=False, postgresql_using='gin')
    op.create_index('ix_rag_chunks_ai_tags', 'rag_chunks', ['ai_tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_rag_chunks_ai_travel_styles', 'rag_chunks', ['ai_travel_styles'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_rag_chunks_chunk_hash'), 'rag_chunks', ['chunk_hash'], unique=False)
    op.create_index(op.f('ix_rag_chunks_city'), 'rag_chunks', ['city'], unique=False)
    op.create_index('ix_rag_chunks_city_place_type', 'rag_chunks', ['city', 'place_type'], unique=False)
    op.create_index(op.f('ix_rag_chunks_country'), 'rag_chunks', ['country'], unique=False)
    op.create_index('ix_rag_chunks_country_city', 'rag_chunks', ['country', 'city'], unique=False)
    op.create_index(op.f('ix_rag_chunks_document_id'), 'rag_chunks', ['document_id'], unique=False)
    op.create_index('ix_rag_chunks_embedding', 'rag_chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_rag_chunks_place_type'), 'rag_chunks', ['place_type'], unique=False)
    op.create_index(op.f('ix_rag_chunks_province'), 'rag_chunks', ['province'], unique=False)
    op.create_index('ix_rag_chunks_search_vector', 'rag_chunks', [sa.literal_column("to_tsvector('english', chunk_text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_rag_chunks_source_chunk_id'), 'rag_chunks', ['source_chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_chunks_source_chunk_id'), table_name='rag_chunks')
    op.drop_index('ix_rag_chunks_search_vector', table_name='rag_chunks', postgresql_using='gin')
    op.drop_index(op.f('ix_rag_chunks_province'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_place_type'), table_name='rag_chunks')
    op.drop_index('ix_rag_chunks_embedding', table_name='rag_chunks', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_rag_chunks_document_id'), table_name='rag_chunks')
    op.drop_index('ix_rag_chunks_country_city', table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_country'), table_name='rag_chunks')
    op.drop_index('ix_rag_chunks_city_place_type', table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_city'), table_name='rag_chunks')
    op.drop_index(op.f('ix_rag_chunks_chunk_hash'), table_name='rag_chunks')
    op.drop_index('ix_rag_chunks_ai_travel_styles', table_name='rag_chunks', postgresql_using='gin')
    op.drop_index('ix_rag_chunks_ai_tags', table_name='rag_chunks', postgresql_using='gin')
    op.drop_index('ix_rag_chunks_ai_suitable_for', table_name='rag_chunks', postgresql_using='gin')
    op.drop_index('ix_rag_chunks_ai_activities', table_name='rag_chunks', postgresql_using='gin')
    op.drop_table('rag_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
