"""clean up

Revision ID: cfc648d0d2a2
Revises: c37f93b458c6
Create Date: 2026-06-10 22:55:00.914451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc648d0d2a2'
down_revision: Union[str, Sequence[str], None] = 'c37f93b458c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_location', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('raw_markdown', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('extraction_method', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('chunking_method', sa.Text(), nullable=True))
    op.alter_column('documents', 'document_type',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_documents_ingestion_status'), 'documents', ['ingestion_status'], unique=False)
    op.create_index(op.f('ix_documents_language'), 'documents', ['language'], unique=False)
    op.create_index(op.f('ix_documents_source_location'), 'documents', ['source_location'], unique=False)
    op.create_unique_constraint('uq_documents_type_file_hash', 'documents', ['document_type', 'file_hash'])
    op.create_unique_constraint('uq_documents_type_source_location', 'documents', ['document_type', 'source_location'])
    op.drop_column('documents', 'source_name')
    op.drop_column('documents', 'chunk_count')
    op.drop_column('documents', 'title')
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'raw_content')
    op.drop_column('documents', 'country')
    op.drop_column('documents', 'source_type')
    op.drop_column('documents', 'source_file')
    op.add_column('rag_chunks', sa.Column('page_number', sa.Integer(), nullable=True))

    op.drop_index(op.f('ix_rag_chunks_source_chunk_id'), table_name='rag_chunks')
    op.create_index(op.f('ix_rag_chunks_place_name'), 'rag_chunks', ['place_name'], unique=False)
    op.create_unique_constraint('uq_rag_chunks_document_chunk_hash', 'rag_chunks', ['document_id', 'chunk_hash'])
    op.drop_column('rag_chunks', 'source_chunk_id')
    op.drop_column('rag_chunks', 'subsection_heading')
    op.drop_column('rag_chunks', 'metadata_source')
    op.drop_column('rag_chunks', 'quality_score')
    op.drop_column('rag_chunks', 'section_level')
    op.drop_column('rag_chunks', 'metadata_confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_chunks', sa.Column('metadata_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rag_chunks', sa.Column('section_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rag_chunks', sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('rag_chunks', sa.Column('metadata_source', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rag_chunks', sa.Column('subsection_heading', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('rag_chunks', sa.Column('source_chunk_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_rag_chunks_document_chunk_hash', 'rag_chunks', type_='unique')
    op.drop_index(op.f('ix_rag_chunks_place_name'), table_name='rag_chunks')
    op.create_index(op.f('ix_rag_chunks_source_chunk_id'), 'rag_chunks', ['source_chunk_id'], unique=False)

    op.drop_column('rag_chunks', 'page_number')
    op.add_column('documents', sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('source_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('raw_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('source_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('chunk_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('source_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_documents_type_source_location', 'documents', type_='unique')
    op.drop_constraint('uq_documents_type_file_hash', 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_source_location'), table_name='documents')
    op.drop_index(op.f('ix_documents_language'), table_name='documents')
    op.drop_index(op.f('ix_documents_ingestion_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.alter_column('documents', 'document_type',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('documents', 'chunking_method')
    op.drop_column('documents', 'extraction_method')
    op.drop_column('documents', 'raw_markdown')
    op.drop_column('documents', 'file_hash')
    op.drop_column('documents', 'source_location')
    # ### end Alembic commands ###
